modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${issueTrackerUrl}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''${description}'''
displayURL = "${websiteUrl}"
updateJSONURL = "${forgeUpdateUrl}"
itemIcon = "minecraft:snowball"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoForgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "immersivesnow.neoforge.mixins.json"

[[mixins]]
config = "immersivesnow.mixins.json"
