name: "CI"
on:
  pull_request: { types: [ opened, reopened ] }
  push:
  workflow_dispatch:

jobs:
  build:
    name: "Build for ${{ matrix.mc }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix: { mc: [ "1.20.4", "1.21.1", "1.21.4" ] }

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with: { distribution: "temurin", java-version: "21" }

      - name: "Setup Cache"
        uses: actions/cache@v4
        with:
          path: "~/.gradle/caches\n~/.gradle/wrapper"
          key: "${{ matrix.mc }}-${{ hashFiles('**/*.gradle*') }}"
          restore-keys: "${{ matrix.mc }}"

      - name: "Compile Mod for ${{ matrix.mc }}"
        run: "./gradlew build --no-daemon -Pminecraft=${{ matrix.mc }}"

      - name: "Upload Fabric Artifacts"
        uses: actions/upload-artifact@v4
        with: { name: "Fabric ${{ matrix.mc }}", path: "fabric/build/libs" }

      - name: "Upload Forge Artifacts"
        uses: actions/upload-artifact@v4
        with: { name: "Forge ${{ matrix.mc }}", path: "forge/build/libs" }

      - name: "Upload NeoForge Artifacts"
        uses: actions/upload-artifact@v4
        with: { name: "NeoForge ${{ matrix.mc }}", path: "neoforge/build/libs" }
